<a href="https://colab.research.google.com/github/daryabiparva/pc_algorithm/blob/master/Copy_of_pcAlgorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


### **Firsts we need to creat our data such that:**
 
#$ y_a  = e_a \\
y_b = 0.5*y_a +0.5*e_b \\
y_c = 0.5*y_a + 0.5*e_c \\
y_d = \frac{1}{\sqrt{3}}y_b + \frac{1}{\sqrt{3}}y_c +\frac{1}{\sqrt{3}}e_d \\
y_e = 0.5* y_d +\frac{1}{3} e_e $




In [0]:
mean = 0
variance = 1

In [0]:
eA=np.random.normal(mean,variance,10000)

In [0]:
eA = np.random.normal(mean, variance, 10000)

In [0]:
eB = np.random.normal(mean, variance, 10000)
eC = np.random.normal(mean, variance, 10000)
eD = np.random.normal(mean, variance, 10000)
eE = np.random.normal(mean, variance, 10000)

In [0]:
yA=eA
yB = 0.5*yA + 0.5*eB
yC=0.5*yA + 0.5*eC
yD = 1/(np.sqrt(3))*yB + 1/(np.sqrt(3))*yC + 1/(np.sqrt(3))*eD
yE= 0.5*yD + 1/3 *eE

In [0]:
eAlist=[i for i in yA]
eBlist=[i for i in yB]
eClist=[i for i in yC]
eDlist = [i for i in yD]
eElist = [i for i in yE]
data_dict = {'A': eAlist, 'B':eBlist, 'C':eClist, 'D':eDlist, 'E':eElist}

In [0]:
#firts implementation 
###wrong
def omitedge(allE, num):
  countall=0
  countindep =0
  for i in range(num):
    for j in range(num):
      for k in range(num):
        if((i != j) and (i != k) and (j != k)):
          countall +=1
          e3conc= [allE[i],allE[j],allE[k]]
          conv= np.cov(e3conc)
          concen = np.linalg.inv(conv)
          
          if(concen[0][1] < 0.0001):
            print(i,'and', j,'conditionally independent on', k)
            countindep += 1
            break
  print('countall:', countall)
  print('countindepe: ', countindep)


### **Using a dictionary to show the graph**

In [0]:
graph={'A':['B','C','D','E'],'B':['A','C','D','E'],'C':['A','B','D','E'], 'D':['A','B','C','E'], 'E':['A','B','C','D']}

In [0]:
    def find_shortest_path(graph, start, end, path=[]):
        path = path + [start]
        if start == end:
            return path
        if start not in graph:
            return None
        shortest = None
        for node in graph[start]:
            if node not in path:
                newpath = find_shortest_path(graph, node, end, path)
                if newpath:
                    if not shortest or len(newpath) < len(shortest):
                        shortest = newpath
        return shortest

In [0]:
find_shortest_path(graph,'A','B')

['A', 'B']

In [0]:
def is_edge(graph_, start, end):
  if (end in graph_[start]):
    return True

  return False

In [0]:
is_edge(graph,'A','C')

True

In [0]:
def find_cardinality(graph_, v1, v2):
  verts = graph_[v1]
  if v2 in verts:
    return ( len(verts) - 1 )
  else:
    print("not adjacent ")
    return len(verts)

In [0]:
def is_independent(dict_data, thresh, n):
  print("inside is independent")
  print("n is equal {}".format(n))
  if n == 0:
    conv =np.cov(dict_data)
    print(conv)
    if(np.absolute(conv[0][1]) < thresh):
      print(X,'and', Y,'independant')
      print("omit edge ")
      return True
    else:
      return False
  
  conv= np.cov(dict_data)
  #print("for {} and {} and {} the covariance matrix is {}".format(X,Y,S,conv))
  concen = np.linalg.inv(conv)
  print(concen)
  if(np.absolute(concen[0][1]) < thresh):
    #print(X,'and', Y,'conditionally independent on', S)
    print("omit edge ")
    return True
  else:
    return False
    

In [0]:
def is_independent_f_test(dict_data, thresh, n):
  m_ = n +2
  n_ = 10000
  dict_data_arr = np.array(dict_data)
  total_mean = np.mean(dict_data_arr)
  each_mean = np.mean(dict_data_arr, axis = 1)
  print("n is {}, mean_vector is {}, mean is  {}".format(n,each_mean,total_mean))
  ssw = 0
  i= 0
  for data_list in dict_data_arr:
    for data_point in data_list:
      ssw = ssw+ (data_point - each_mean[i])**2
    i = i+1
  ssb = 0
  for mean in each_mean:
    ssb = ssb+ n_*((mean - total_mean)**2)
  print("ssw is {}, ssb is {} ".format(ssw,ssb))
  df1 = m_ - 1
  #df2 = m_*(n_ - 1) #it is counted as inf
  F_limit = [2.7055,2.3026,2.0838]
  f =(ssb /(m_ -1))/(ssw/(m_*(n_ - 1)))
  print("f is {}".format(f))
  if (f > F_limit[m_ - 2]):
    return True
  else:
    return False


In [0]:
#making the sepsets:
sepsets={'AB': 0, 'AC': 0, 'AD':0,'AE':0,'BA':0,'BC':0, 'BD':0, 'BE':0,'CA':0,'CB':0,'CD':0,'CE':0,'DA':0,'DB':0,'DC':0,'DE':0,'EA':0,'EB':0,'EC':0,'ED':0}

In [0]:
import itertools
def findsubsets(S,m):
    return set(itertools.combinations(S, m))

In [0]:
#first order dependicies:

n = 1
vertex_set = ['A','B','C','D','E']
vertex_set2 = ['A','B']
threshs= [0.1]
for thresh in threshs:
  
  graph={'A':['B','C','D','E'],'B':['A','C','D','E'],'C':['A','B','D','E'], 'D':['A','B','C','E'], 'E':['A','B','C','D']}
  sepsets={'AB': 0, 'AC': 0, 'AD':0,'AE':0,'BA':0,'BC':0, 'BD':0, 'BE':0,'CA':0,'CB':0,'CD':0,'CE':0,'DA':0,'DB':0,'DC':0,'DE':0,'EA':0,'EB':0,'EC':0,'ED':0}
  for X in vertex_set:
    for Y in vertex_set:
      print(X,Y)
      if (X != Y):
        if(is_edge(graph, X, Y)):
          flag_not_omitted = True
          n=0
          adjacencies_exY= [graph[X][i] for i in range(len(graph[X])) if (graph[X][i] != Y)]
          while(find_cardinality(graph, X,Y)>(n-1) and flag_not_omitted):
            print("inside the while with n = {}".format(n))
            set_S=findsubsets(adjacencies_exY,n)
            for s in set_S:
              print(s)
              if n == 0 :
                print("in the if with n= {}".format(n))
                data = [data_dict[X], data_dict[Y]]
                print("is_indep is {}, and is_indep_f_test is {} ".format(is_independent(data,thresh,n), is_independent_f_test(data,thresh, n)))
                if is_independent(data, thresh, n):

                  print("omit edge between ", X, Y)
                  print(graph[X])
                  print(Y)
                  (graph[X]).remove(Y)
                  (graph[Y]).remove(X)
                  sepsets[X+Y] = s
                  sepsets[Y+X] = s
                  flag_not_omitted = False
                  break
              if n == 1:
                  print("in the if with n= {}".format(n))
                  data = [data_dict[X], data_dict[Y], data_dict[s[0]]]
                  print("is_indep is {}, and is_indep_f_test is {} ".format(is_independent(data,thresh,n), is_independent_f_test(data,thresh, n)))
                  if is_independent(data, thresh, n):
                    print("omit edge between ", X, Y)
                    (graph[X]).remove(Y)
                    (graph[Y]).remove(X)
                    sepsets[X+Y] = s
                    sepsets[Y+X] = s
                    flag_not_omitted = False
                    print(graph[X])
                    print(Y)
                    break
              if n == 2:
                  print("in the if with n= {}".format(n))
                  data = [data_dict[X], data_dict[Y], data_dict[s[0]], data_dict[s[1]]]
                  print("is_indep is {}, and is_indep_f_test is {} ".format(is_independent(data,thresh,n), is_independent_f_test(data,thresh, n)))
                  if is_independent(data, thresh, n):
                    print("omit edge between ", X, Y)
                    (graph[X]).remove(Y)
                    (graph[Y]).remove(X)
                    print(graph[X])
                    print(Y)
                    sepsets[X+Y] = s
                    sepsets[Y+X] = s
                    flag_not_omitted = False
                    break
            print("\n")
            n= n+1
          #   adjacencies_exY= [graph[X][i] for i in range(len(graph[X])) if (graph[X][i] != Y)]
            #  print("X is " + X + ", Y is "+ Y + " and the list: " )
            # print(adjacencies_exY)
              #print("\n")
              #now we have the set, let's check independence
            #  for S in adjacencies_exY:
            #   if is_independent(data_dict, X,Y,S, thresh):
              #    print("omit edge between ", X, Y)
              #   print(graph[X])
                #  print(Y)
              #   (graph[X]).remove(Y)
                #  (graph[Y]).remove(X)
                # sepsets[X+Y] = S
                # sepsets[Y+X] = S
                # break
            
  print("this {}, is the graph for {}".format(graph, thresh))
  print("the sepset for threshold {} is: \n {}".format(thresh, sepsets))

A A
A B
inside the while with n = 0
()
in the if with n= 0
inside is independent
n is equal 0
[[1.00000022 0.49771616]
 [0.49771616 0.49417651]]
n is 0, mean_vector is [ 0.01181399 -0.00330357], mean is  0.004255209806696382
ssw is 14940.27317861264, ssb is 1.1427042368483002 
f is 1.5295436070878015
is_indep is False, and is_indep_f_test is False 
inside is independent
n is equal 0
[[1.00000022 0.49771616]
 [0.49771616 0.49417651]]


inside the while with n = 1
('E',)
in the if with n= 1
inside is independent
n is equal 1
[[ 2.09395944 -1.82840934 -0.63828506]
 [-1.82840934  4.46863662 -1.37318448]
 [-0.63828506 -1.37318448  4.58676109]]
n is 1, mean_vector is [ 0.01181399 -0.00330357  0.00437893], mean is  0.004296451470855175
ssw is 18171.418587492095, ssb is 1.1428062893400555 
f is 0.9432604311071803
is_indep is False, and is_indep_f_test is False 
inside is independent
n is equal 1
[[ 2.09395944 -1.82840934 -0.63828506]
 [-1.82840934  4.46863662 -1.37318448]
 [-0.63828506 -1.3731

In [0]:
print(graph)

{'A': ['B', 'C', 'D', 'E'], 'B': ['A', 'C', 'D', 'E'], 'C': ['A', 'B', 'D', 'E'], 'D': ['A', 'B', 'C', 'E'], 'E': ['A', 'B', 'C', 'D']}


In [0]:
concat=[yA,yB]
np.cov(concat)

array([[0.99716807, 0.50347074],
       [0.50347074, 0.51049091]])

In [0]:
#directing
#AB=1 A to B
#AB = 2 B to A
graph = {'A': ['B', 'C'], 'B': ['A', 'D'], 'C': ['A', 'D'], 'D': ['B', 'C', 'E'], 'E': ['D']}
sepsets = {'AB': (), 'AC': (), 'AD': ('B', 'C'), 'AE': ('B', 'C'), 'BA': (), 'BC': ('A',), 'BD': (), 'BE': ('D',), 'CA': (), 'CB': ('A',), 'CD': (), 'CE': ('D',), 'DA': ('B', 'C'), 'DB': (), 'DC': (), 'DE': (), 'EA': ('B', 'C'), 'EB': ('D',), 'EC': ('D',), 'ED': ()}
vertex_set = ['A','B','C','D','E']
arrows = {'AB': 0, 'AC': 0, 'AD':0,'AE':0,'BA':0,'BC':0, 'BD':0, 'BE':0,'CA':0,'CB':0,'CD':0,'CE':0,'DA':0,'DB':0,'DC':0,'DE':0,'EA':0,'EB':0,'EC':0,'ED':0}
for X in vertex_set:
  for Y in vertex_set:
    for Z in vertex_set:
      if (X != Y and X != Z and Y != Z):
        if(is_edge(graph, X, Y) and is_edge(graph, Y,Z)):
          if(is_edge(graph,X,Z) == 0):
            print("X is {}, Y is {}, Z is {}".format(X,Y,Z))
            print("sepset x z is {}".format(sepsets[X+Z]))
            if ((Y in sepsets[X+Z]) == 0):
              print("made it")
              arrows[X+Y] = 1
              arrows[Y+X] = 2
              arrows[Y+Z] = 2
              arrows[Z+Y] = 1
flag_all_not_oriented = True
#while(flag_all_not_oriented):
for i in range(4):
  for X in vertex_set:
    for Y in vertex_set:
      for Z in vertex_set:
        if (X != Y and X != Z and Y != Z):
          if(arrows[X+Y] == 1):
            if(arrows[Y+Z]==0):
              if(is_edge(graph, Y,Z) and (is_edge(graph,X,Z)== 0)):
                print("second way, X is {}, Y is {}, Z is {}".format(X,Y,Z))
                arrows[Y+Z] = 1
                arrows[Z+Y] = 2
                #flag_all_not_oriented= False
                #for key in arrows:

                  #if(arrows[key]==0):
                    #flag_all_not_oriented = True
                    


X is A, Y is B, Z is D
sepset x z is ('B', 'C')
X is A, Y is C, Z is D
sepset x z is ('B', 'C')
X is B, Y is A, Z is C
sepset x z is ('A',)
X is B, Y is D, Z is C
sepset x z is ('A',)
made it
X is B, Y is D, Z is E
sepset x z is ('D',)
X is C, Y is A, Z is B
sepset x z is ('A',)
X is C, Y is D, Z is B
sepset x z is ('A',)
made it
X is C, Y is D, Z is E
sepset x z is ('D',)
X is D, Y is B, Z is A
sepset x z is ('B', 'C')
X is D, Y is C, Z is A
sepset x z is ('B', 'C')
X is E, Y is D, Z is B
sepset x z is ('D',)
X is E, Y is D, Z is C
sepset x z is ('D',)
second way, X is B, Y is D, Z is E


In [0]:
print(arrows)
print(sepsets)

{'AB': 0, 'AC': 0, 'AD': 0, 'AE': 0, 'BA': 0, 'BC': 0, 'BD': 1, 'BE': 0, 'CA': 0, 'CB': 0, 'CD': 1, 'CE': 0, 'DA': 0, 'DB': 2, 'DC': 2, 'DE': 1, 'EA': 0, 'EB': 0, 'EC': 0, 'ED': 2}
{'AB': (), 'AC': (), 'AD': ('B', 'C'), 'AE': ('B', 'C'), 'BA': (), 'BC': ('A',), 'BD': (), 'BE': ('D',), 'CA': (), 'CB': ('A',), 'CD': (), 'CE': ('D',), 'DA': ('B', 'C'), 'DB': (), 'DC': (), 'DE': (), 'EA': ('B', 'C'), 'EB': ('D',), 'EC': ('D',), 'ED': ()}
